all:
	gcc -o quicksort quicksort.c
	gcc -o auto-advisor auto-advisor.c
	gcc -o matrix-multiplication matrix-multiplication.c
	
clean:
	@rm -f quicksort auto-advisor matrix-multiplication
	@rm -f *.ll *.bc