quicksort:
	gcc -o quicksort quicksort.c

auto-advisor:
	gcc -o auto-advisor auto-advisor.c

matrix-multiplication:
	gcc -o matrix-multiplication matrix-multiplication.c
 
clean:
	@rm -f quicksort auto-advisor matrix-multiplication